# Generated by Django 5.0.1 on 2024-01-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPTCommunication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='inputDataName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
