# Generated by Django 5.0.1 on 2024-01-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPTCommunication', '0002_interaction_inputdataname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interaction',
            name='inputDataName',
        ),
        migrations.AddField(
            model_name='interaction',
            name='inputData',
            field=models.FileField(null=True, upload_to='uploads'),
        ),
    ]
