# Generated by Django 5.0.1 on 2024-01-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPTCommunication', '0003_remove_interaction_inputdataname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputData', models.FileField(upload_to='uploads')),
            ],
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='inputData',
        ),
    ]
