# Generated by Django 5.0.1 on 2024-01-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPTCommunication', '0005_dataupload_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequirementsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RequirementName', models.CharField(max_length=100)),
                ('RequirementDescription', models.TextField()),
            ],
        ),
    ]
