# Generated by Django 5.0.1 on 2024-01-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPTCommunication', '0006_requirementslist'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementslist',
            name='RequirementID',
            field=models.IntegerField(null=True),
        ),
    ]
