# Generated by Django 5.0.1 on 2024-01-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPTCommunication', '0007_requirementslist_requirementid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirementslist',
            name='id',
        ),
        migrations.AlterField(
            model_name='requirementslist',
            name='RequirementID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
