# Generated by Django 5.0.1 on 2024-01-20 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GPTCommunication', '0009_rename_requirementdescription_requirementslist_requirementdescription_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Interaction',
        ),
    ]
